var index = [
{'name': 'com.vasileff.ceylon.random.api', 'type': 'package', 'url': 'index.html#section-package', 'doc': '', 'tags': [],'icons': ['icon-package']},
{'name': 'Random.nextBits', 'type': 'function', 'url': 'Random.type.html#nextBits', 'doc': '<p>Generates an Integer holding <code>numBits</code> pseudorandom bits.</p>\n', 'tags': [],'icons': ['icon-shared-member', 'icon-decoration-formal']},
{'name': 'Random.nextInteger', 'type': 'function', 'url': 'Random.type.html#nextInteger', 'doc': '<p>Returns the next pseudorandom <code>Integer</code> between <code>0</code> (inclusive)\nand <a class=\'link\' href=\'Random.type.html#nextInteger-bound\' title=\'Go to com.vasileff.ceylon.random.api::Random.nextInteger.bound\'><code><span class=\'identifier\'>bound</span></code></a> (exclusive).</p>\n', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'Random.nextBoolean', 'type': 'function', 'url': 'Random.type.html#nextBoolean', 'doc': '<p>Returns the next pseudorandom <code>Boolean</code>.</p>\n', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'Random.nextByte', 'type': 'function', 'url': 'Random.type.html#nextByte', 'doc': '<p>Returns the next pseudorandom <code>Byte</code>.</p>\n', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'Random.nextFloat', 'type': 'function', 'url': 'Random.type.html#nextFloat', 'doc': '<p>Returns the next pseudorandom <code>Float</code> between <code>0.0</code> and <code>1.0</code>.</p>\n', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'Random', 'type': 'interface', 'url': 'Random.type.html', 'doc': '<p>An interface for random number generators.</p>\n', 'tags': [],'icons': ['icon-interface']},
{'name': 'randomLimits.maxIntegerBound', 'type': 'value', 'url': 'randomLimits.object.html#maxIntegerBound', 'doc': '<p>The largest value that may be used as an argument to <a class=\'link\' href=\'Random.type.html#nextInteger\' title=\'Go to com.vasileff.ceylon.random.api::Random.nextInteger\'><code><span class=\'type-identifier\'>Random</span>.<span class=\'identifier\'>nextInteger()</span></code></a>.</p>\n', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'randomLimits.maxBits', 'type': 'value', 'url': 'randomLimits.object.html#maxBits', 'doc': '<p>The largest value that may be used as an argument to <span class=\'link-unresolvable\'><code>Random.nextBits</code></span>.</p>\n', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'randomLimits', 'type': 'object', 'url': 'randomLimits.object.html', 'doc': '<p>Provides limits relevant to generating random numbers on the current runtime.</p>\n', 'tags': [],'icons': ['icon-object']},
{'name': 'randomLimits', 'type': 'value', 'url': 'index.html#randomLimits', 'doc': '<p>Provides limits relevant to generating random numbers on the current runtime.</p>\n', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'stream', 'type': 'function', 'url': 'index.html#stream', 'doc': '<p>Produces the <span title=\'ceylon.language::Iterable\'>stream</span> that results from repeated\ncalls to the given <a class=\'link-custom-text\' href=\'index.html#stream-next\' title=\'Go to com.vasileff.ceylon.random.api::stream.next\'>function</a>.</p>\n', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'com.vasileff.ceylon.random.api', 'type': 'module', 'url': 'index.html', 'doc': '', 'tags': [],'icons': []}];
var tagIndex = [
];
